### ISSUE TITLE
Time needs to be synced up on Phones

### ISSUE THREAD

**Issue by nipunbatra** [nipunbatra/Home_Deployment#15]

**Comment by shailja-thakur** [comment]
Might be because of turning then on and off many times .

**Comment by nipunbatra** [comment]
Again saw that one of the phone was out of sync. Since getting new sim for all of them is not easy, putting them all on WiFi. Will observe if they choke up the b/w or not.

**Comment by amarjeet-iiitd** [comment]
Nipun, did one of the phones already had a SIM?

Also check with Siddhartha. He purchased 6 sims for his work. They may not
be getting used or he can get more from the same vendor if you want.

Best regards
Amarjeet Singh

**Comment by amarjeet-iiitd** [comment]
I also think that out of sync might be happening because of phone reboot
for some reason.

Best regards
Amarjeet Singh

**Comment by nipunbatra** [comment]
All phones are put on perpetual charging, so they  should not be reset. I think putting them on network should solve the issue. Only 1 phone has been giving problem. Will update the status tomorrow.

**Comment by shailja-thakur** [comment]
Only solution would be keep them connected to wifi

And how much data is already collected , isn't there by now any space
shortage?

**Comment by nipunbatra** [comment]
I would leave them connected to WiFi. How do we check if the phone is running out of space?

**Comment by amarjeet-iiitd** [comment]
Keep checking the size of file created by the application. You can also
check system information by going to storage in settings.

Best regards
Amarjeet Singh
