### ISSUE TITLE
Multisensor Plot should show PIR=0 default and 1 o/w

### ISSUE THREAD

**Issue by nipunbatra** [nipunbatra/Home_Deployment#26]
This is how it looks currently.
![ckpjrqqzaovc](https://f.cloud.github.com/assets/60985/572993/b77a749c-c7a7-11e2-9a21-75d94fe75061.jpg)

**Comment by milan1267** [comment]
It will give you timestamp whenever there would be motion, so by default we have to assume it as 0.
