### ISSUE TITLE
No data from a particular node

### ISSUE THREAD

**Issue by nipunbatra** [nipunbatra/Home_Deployment#27]
Node number 4  which is actually the closest to the ZStick didn't send any data after a certain time. It was working on inverter point and would have had power even when electricity went. Could this be the issue? This is critical to figure out. Should i reset Plug Computer?

**Comment by milan1267** [comment]
Ya because Node searches for a controller, and when power goes off as there was no controller, it goes to sleep mode and may be when light came back, it was in sleep mode and not configured according to the settings we are using in our program.

**Comment by nipunbatra** [comment]
Removed the node from inverter point. Data coming in a continuous fashion since.
