### ISSUE TITLE
Noisy SMPS

### ISSUE THREAD

**Issue by nipunbatra** [nipunbatra/Home_Deployment#29]
SMPS makes a little noise. Have seen this before. Want to confirm what noise level is permissible.

**Comment by manojgulati** [comment]
The room where you have installed your desktop is usually hot also a lot of dust is accumulating there. Please move the desktop to a better place. Cleaning SMPS fan might help.

**Comment by nipunbatra** [comment]
Noise levels at an all time high. Previous experience with laptop shows that it may shutdown due to over heating. Need to clean the fan.

**Comment by nipunbatra** [comment]
Cleaned the Desktop. Literally a kg of dust!! Will add this as a unique aspect of Indian deployments in forthcoming paper.
