### ISSUE TITLE
Desktop (Main server) may not start, due to serial command from CC  

### ISSUE THREAD

**Issue by nipunbatra** [nipunbatra/Home_Deployment#30]

**Comment by nipunbatra** [comment]
Simple solution would be to get another RPi and store data there

**Comment by amarjeet-iiitd** [comment]
What is CC?

On Sat, Jun 1, 2013 at 11:32 AM, Nipun Batra notifications@github.comwrote:

> Simple solution would be to get another RPi and store data there
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nipunreddevil/Home_Deployment/issues/30#issuecomment-18784242
> .

## 

Best Regards

Amarjeet Singh,
Asst. Professor, IIIT Delhi
http://www.iiitd.edu.in/~amarjeet/

**Comment by nipunbatra** [comment]
CC: Current Cost

**Comment by amarjeet-iiitd** [comment]
We now have 2 extra RPis that you can use for the deployment.

On Sat, Jun 1, 2013 at 12:01 PM, Nipun Batra notifications@github.comwrote:

> CC: Current Cost
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nipunreddevil/Home_Deployment/issues/30#issuecomment-18784493
> .

## 

Best Regards

Amarjeet Singh,
Asst. Professor, IIIT Delhi
http://www.iiitd.edu.in/~amarjeet/

**Comment by nipunbatra** [comment]
Replaced with RPi. Doing local storage on RPi now. The method is reliable so shouldn't be an issue.
