### ISSUE TITLE
Zwave program was stopped

### ISSUE THREAD

**Issue by nipunbatra** [nipunbatra/Home_Deployment#31]
Need error logging for the Python script. Several times now i have seen that the Python program is not running.

**Comment by nipunbatra** [comment]
Found that Plug Computer was out of space. The Logs had consumed all the space. Cleared all the logs for now. The logs by themself had taken about 50% of Disk Space.

**Comment by nipunbatra** [comment]
There was some error with run.py file. For some reason it's contents were nil. Copied this file again from github and now the program atleast starts. I think, when space was full, something happened, which forced contents of run.py to be nil.

**Comment by nipunbatra** [comment]
Will need to add a script to delete older log files to ensure that disk does not get full. Also will run the script to alert in such events.

**Comment by amarjeet-iiitd** [comment]
Try to maintain logs at a lower frequency but for the whole deployment.

Please do collect logs about network connectivity as well. Maybe just run
ping for 15 consecutive minutes and then store the summary characteristics
that come at the end and then restart ping.

Best regards
Amarjeet Singh

**Comment by nipunbatra** [comment]
Current logs include the following:
- Disk Space
- RAM
- CPU
- Local Time 

I would try and see if i can add those ping statistics here as well. In general, connectivity has been good.

**Comment by amarjeet-iiitd** [comment]
We want to make an argument later for hosting local desktop for data
collection. Collecting network statistics, even at 5-15 minute resolution
will help.

Best regards
Amarjeet Singh

**Comment by nipunbatra** [comment]
Added a script to remove older log files from plug computer. Now it should not eat up the entire disk space.
