### ISSUE TITLE
CT Circuit #2 

### ISSUE THREAD

**Issue by manojgulati** [nipunbatra/Home_Deployment#50]
Ashish tested new CT circuit having 4 CT's and arduino as host controller for 2 hours. Its working fine. Please inform if you want to test anything else before we send this for actual deployment.

Also kind of casing you aspect as ground floor panel box was hardly having any free space  inside that.

**Comment by nipunbatra** [comment]
- Test for 5 CT's
- Regarding casing you already know what to put based on the size
